### ISSUE TITLE
Restrict Aircraft At Departure settings causes ACARS and manual PIREPs to reject usage of aircraft

### ISSUE THREAD

**Issue by hcshires** [nabeelio/phpvms#781] opened 2020-08-04 22:13 UTC
**Describe the bug**
When the airline setting, "Restrict Aircraft At Departure Settings", is enabled, both manual PIREPS and ACARS auto filing reject the ability to use an aircraft, even if it is located at the same departure airport as the flight. 

**Version**
v7.0.0beta4

**To Reproduce**
1. Go to the Admin page
2. Click on settings
3. Scroll down to "Restrict Aircraft At Departure"
4. Enable setting
5. Move an aircraft to the desired airport
6. Select a bid with the same departure airport as the location of the aircraft
7. File a PIREP for your selected bid
8. Enter desired information, given that the aircraft and departure airport is the same as above
9. View the error, "Can't submit, the selected aircraft is not at the departure airport"

**Expected behavior**
When the aircraft is at the same airport as the departure location on the flight, the aircraft should be eligible to use, rather than rejecting and giving an error.

**Comment by nabeelio** [comment] 2020-08-12 22:27
This is a duplicate of #685

**Comment by nabeelio** [comment] 2020-08-12 22:30
Question - is your pilot listed as being at that location already?

**Comment by hcshires** [comment] 2020-08-12 22:32
They are.

**Comment by nabeelio** [comment] 2020-08-13 22:12
Do you have the exact error string?

**Comment by nabeelio** [comment] 2020-08-13 22:16
Can you also try the latest dev, I can't duplicate this one

**Comment by hcshires** [comment] 2020-08-14 14:28
Yes I will do this and follow up

**Comment by nabeelio** [comment] 2020-08-14 14:44
I think I have a fix in that branch, if you could test that out?

**Comment by hcshires** [comment] 2020-08-14 20:27
Yes I can

**Comment by hcshires** [comment] 2020-08-16 15:41
So sorry I took forever to test this. The issue is fixed when filing a manual PIREP (frontend) but when using ACARS aka API, the same issue occurs. (Error: The aircraft is not at the departure airport)

**Comment by nabeelio** [comment] 2020-08-17 20:17
D'oh! That should be fixed now too

**Closed** 2020-08-17 20:44 UTC
Labels: bug

**Comment by hcshires** [comment] 2020-08-17 20:53
Yep this fixed it!
