### ISSUE TITLE
Ranks Seeder runs on every module install (Bug Report)

### ISSUE THREAD

**Issue by FatihKoz** [nabeelio/phpvms#1351] opened 2021-11-14 21:13 UTC
```
[2021-11-14 19:55:40] production.INFO: Running seeder  
[2021-11-14 19:55:40] production.INFO: Seeding .D:\Projects\phpvms/app/Database\seeds/prod/ranks.yml 
```
Seeder runs on every module install and seeds `ranks.yml`. This happens for modules without seeds or migrations too.

**Version**
Latest dev as of date

**To Reproduce**
1. Do a fresh install
2. Edit your ranks, specially edit "New Pilot"
3. Install a module
4. Check logs and your ranks
5. New Pilot will be defaulted and the seeding entry will be in the log

**Expected behavior**
If not mandatory for some reason it should not run, or at best it should check if there is a "New Pilot" entry before overwriting it.

**Comment by YashGovekar** [comment] 2022-10-24 15:29
@FatihKoz Did you face the above issue through Module Installer on Admin Panel?

**Comment by FatihKoz** [comment] 2022-10-25 17:01
Does it matter @YashGovekar ?

**Comment by YashGovekar** [comment] 2022-10-26 07:13
> Does it matter @YashGovekar ?

Yes, because something is happening during Module Install step so need to know how's that step done.

**Comment by FatihKoz** [comment] 2022-10-26 19:46
> Yes, because something is happening during Module Install step so need to know how's that step done.

You can try it... It is much faster than asking and waiting for an answer, steps are described above. Even if you want to be sure, you can try doing it in both ways (manual upload and via provided module installer).

Most probably result will be the same.

**Comment by nabeelio** [comment] 2022-10-26 23:12
This one is a little bit tricky to fix

**Comment by arthurpar06** [comment] 2023-10-18 13:59
Hi,

After some tests I was only able to reproduce this bug one way. Have migrations pending on a module, migrations which are executed via the updater. That is to say that if we upload a module / enable it from the module page there is no bug, at least not for me.

When we launch the updater to make the updates it will also launch the [syncAllSeeds](https://github.com/nabeelio/phpvms/blob/dev/app/Services/Installer/SeederService.php#L54) function and in particular [syncAllYamlFileSeeds](https://github.com/nabeelio/phpvms/blob/dev/app/Services/Installer/SeederService.php#L65) function. This function will take the `APP_ENV` (production in our case) and will then seed the files in `/app/Database/seeds/APP_ENV/`. But in `/app/Database/seeds/production/` there is this `ranks.yml` file which creates this "New Pilot" rank. So theoretically moving this file from` /app/Database/seeds/production/` to `/app/Database/seeds/dev/` should be enough to fix the issue.

My question for @nabeelio being is there any specific interest in having this ranks seed in production or not? If not I can do the PR to move it, if yes we will have to find a better solution to correct this bug.

**Comment by nabeelio** [comment] 2023-10-18 15:34
Yea that should be moved into the migration which setups up the rank table, otherwise, it doesn't need to run again

**Closed** 2023-10-18 20:19 UTC
Labels: bug
