### ISSUE TITLE
Download page error, if you delete Airport/Fleet in admin. 

### ISSUE THREAD

**Issue by macofallico** [nabeelio/phpvms#882] opened 2020-10-21 15:48 UTC
[https://flareapp.io/share/yPao64W5](url)

Running Latest Dev Versión

1. Go to 'Airports, Create Airport/fleet'
2. Then Add any File to the airport
3. Check in dowload page (should work ok)
4. Then delete the airport/fleet
5. See the error in the download page.

**Comment by nabeelio** [comment] 2020-10-21 17:25
Fix is deleting any downloads for that asset (fleet, airport, etc). Also, if that airport is being used, or that fleet/aircraft are being used, then don't allow that asset to be deleted (flash an error that it can't be deleted, and just set it to inactive instead). 

@YashGovekar this might be a good one to pick up next

**Comment by nabeelio** [comment] 2020-10-21 17:26
Kinda related to #822 and #434

**Comment by YashGovekar** [comment] 2020-10-21 19:44
Alright, will look into them. Thanks!

**Comment by ArthurHetem** [comment] 2023-08-15 18:18
@nabeelio, can't reproduce this one, probabbly already fixed by #1267.

> Fix is deleting any downloads for that asset (fleet, airport, etc). Also, if that airport is being used, or that fleet/aircraft are being used, then don't allow that asset to be deleted (flash an error that it can't be deleted, and just set it to inactive instead).

This deletion logic still needs to be implemented even after softDeletes?

**Comment by nabeelio** [comment] 2023-08-16 00:48
Yeah we'd delete the downloads, don't think it needs to be soft deleted

**Closed** 2023-08-26 23:57 UTC
Labels: bug
