### ISSUE TITLE
PIREP edit error

### ISSUE THREAD

**Issue by Jannis-D** [nabeelio/phpvms#1244] opened 2021-06-13 09:26 UTC
**Describe the bug**
When editing and saving a pending PIREP, an error will occur. Also the Fares-Amount gets empty.
[laravel-2021-06-13.log](https://github.com/nabeelio/phpvms/files/6643614/laravel-2021-06-13.log)

**Version**
Some recent DEV - version (unable to locate build)

**To Reproduce**
1. Go to your pending PIREP's
2. Click on Edit and edit the PIREP
3. Scroll down to Save & click it.

**Expected behavior**
The PIREP should be saved without the error and fares should be where they are.

**Screenshots**
-

**Additional context**
Problem exists, since some DEV-update.

**Comment by FatihKoz** [comment] 2021-06-13 15:32
Duplicate of #1233

**Closed** 2022-02-24 20:31 UTC
Labels: wontfix
