### ISSUE TITLE
To be able to base Airframe at an Airport rather then subfleet

### ISSUE THREAD

**Issue by dougjuk** [nabeelio/phpvms#1357] opened 2021-11-20 12:08 UTC
At the moment you can only base a subfleet at an Airport (HUb)

**Describe the solution you'd like**
I would like to be able to base the actual aircraft at an Airport.  So for example my German registered A320's can be based at Munich while the British ones at Heathrow. etc.  It would also make it possible to base and Aircraft for a period at another airport for short operations such as summer schedules.

**Describe alternatives you've considered**
Otherwise it means creating duplicate sub fleets

**Comment by nabeelio** [comment] 2021-11-20 19:50
Do you mean setting the initial airport for an aircraft, or having a hub option for an aircraft?

**Comment by dougjuk** [comment] 2021-11-20 21:46
Having the hub option for the aircraft rather than whole sub fleet.

**Comment by isaacessex** [comment] 2021-11-21 13:18
Great idea!

**Comment by FatihKoz** [comment] 2021-11-25 14:00
I think this is a duplicate of #1258 ;)

**Closed** 2021-11-30 19:54 UTC
