### ISSUE TITLE
[Feature] Aircraft wear & Maintenence

### ISSUE THREAD

**Issue by Markanito** [nabeelio/phpvms#901] opened 2020-10-25 18:43 UTC
I came to an idea to add Aircraft Status when creating new aircraft (Status: 0-100%) which will show wear of an aircraft after every flight. After the flight is completed system would reduce status number by certain factor and once when it falls bellow 70% (or any percentage) the plane changes status from Active to Maintenence and is not available for flying.

This could also be connected to Landing Rate and if someone landed with landing rate greater then predefined value it should send aircraft to the hangar for maintenence. 

If it is possible in Admin pannel there should be an option to predefine values for what is considered a crash landing and at what point aircraft should be sent to hangar for maintenence.

**Comment by nabeelio** [comment] 2020-10-25 19:17
Dupe of #758, can you add this information into there, please?

**Closed by nabeelio** 2020-10-25 19:17 UTC
Labels: feature request
